### PR TITLE
Adding app info to makefile

### PR DESCRIPTION
**Pull request by wolfposd**
to deploy create a folder tinfoil with contents:

sdcard/switch/tinfoil/Tinfoil.nacp
sdcard/switch/tinfoil/Tinfoil.nro

### CODE REVIEW

**Comment by Adubbz** [comment]
Thanks for this! Nice icon by the way :)

**Comment by Adubbz** [comment]
I had a look and it seems the icon was taken from some Facebook app. Obvious copyright infringement issues aside, I'd much prefer Tinfoil had its own icon.

**Comment by GhostlyCrowd** [comment]
Its on github but there is attributed no license to the app.

https://github.com/velazcod/Tinfoil-Facebook

**Comment by Adubbz** [comment]
It seems it's Apache 2.0, which does avoid the copyright infringement issue. However, I'm still not too fond of reusing the branding of something else, even if the icon itself does look nice.

**Comment by GhostlyCrowd** [comment]
icon

Bout the best I can do, I'm no pro

**Pull request merged**
