### PR TITLE
more libnx changes

### PR DESCRIPTION
**Pull request by jimzrt**
these changes are needed to get Tinfoil to compile again. (based on master libnx)

### CODE REVIEW

**Comment by Adubbz** [comment]
ncm_ext can probably just be ditched completely, all of those commands are in libnx now

**Comment by jimzrt** [comment]
right, works as well!
is it okay like this or shall i squash the two commits?

**Comment by Adubbz** [comment]
Have you made sure it still builds if you just remove the file with no further changes

**Comment by jimzrt** [comment]
yep

**Pull request merged**
