### PR TITLE
Remove UI, update readme

### PR DESCRIPTION
**Pull request by ITotalJustice**
I hope you're still accepting pr's :)

I've fixed compiling for latest libnx, this is good because of the HID changes which require homebrew to be compiled against latest libnx.
Everything seems to work fine, though let me know if i missed anything.

Thanks!

### CODE REVIEW

**Comment by Adubbz** [comment]
I see you've introduced a dependency on mbedtls, but I'm not really sure why? Also there's not really much point in updating the UI stuff, just nuke it imo.

**Comment by ITotalJustice** [comment]
Thanks for getting back to me 😄 

mbedtls is now needed for using libcurl. And sure I can nuke the UI, i'll update the makefile too. Btw I can make a ui exactly like you wanted in the ui_mockup.png if you would like, I could do it with sdl. I Only did a quick fix for compiling originally because I wasn't sure if wanted any extra work done on the app :)

**Comment by Adubbz** [comment]
Makes sense. I'm happy to merge contributions from others, so if you want to develop the UI you're certainly welcome to. I just don't intend on developing Tinfoil further myself

**Comment by ITotalJustice** [comment]
Thank you so much! I'll nuke the UI and update the readme for now so that people can at least compile. I'll open a separate pr for the new UI as it'll take me a while longer to do.

I'll also try and fix sd card installs which has been broken since fw 7 I believe (in that same fw, it also broke goldleaf, so i'll probably end up just asking xor about it).

**Comment by Adubbz** [comment]
I spoke with blawar and it seems he had already implemented a fix for sd card installs (along with all the other fixes), so I've merged his PR. However, I still welcome (and appreciate!) any UI/README changes (including nuking the old UI stuff)

**Comment by ITotalJustice** [comment]
No problem! That definitely makes it easier for me at least haha. I have removed most of the UI locally, ill just pull the changes made by blawar. I added an icon for the app also, not sure if wanted one or not (will remove if not).

**Comment by ITotalJustice** [comment]
Would this be okay to merge for now? Still compiles fine, everthing works fine also.

And also, like i said there is an included icon for the app now, i can remove if you don't want it :)

**Pull request merged**
